#print('Strip'.strip)
#print('Maiúsculo'.upper)
#print('minúsculo'.lower)
#print('T,exto,c,o,m,vá,ria,s v, ir, g, ulas'.replace())
#print('texto teste para fução count'.count())
#print('Texto centralizado'.center())
#print('Avião'.index())
#print('alfanumrico'.isnumeric)
#print('teste de quebra de string com split'.split)
#print('este é um titulo'.title())
#print('este é um titulo'.capitalize())
#print('456'.zfill(5))
